@startuml
autonumber
skinparam sequenceMessageAlign center
skinparam actorStyle hollow

actor "Utilisateur" as user
actor "Modérateur" as mod
participant "Application" as app

note over user, app
L’utilisateur n'est pas encore inscrit
end note

user -> app : Remplit formulaire d'inscription
app -> app : Vérifie si toutes les informations sont complètes
alt Formulaire incomplet
    app -> user : Rejette et affiche message d'erreur
end
    app -> mod : Transmet formulaire et document(s) d'identité(s) pour validation
    mod -> app : Accepte ou refuse l'inscription
    app -> user : Informe de la décision du modérateur

@enduml
