@startuml
autonumber
skinparam sequenceMessageAlign center
skinparam actorStyle hollow

actor "Utilisateur" as user
participant "Application" as app

note over user, app
L’utilisateur inscrit et authentifié
end note

user -> app : L'utilisateur appuie sur un bouton pour decouvrir de nouveaux profils
app -> user : L'application propose des profils en fonction des critères de selection

note over user, app
    La recherche de profil ce fait dans la partie qui propose automatiquement des profils, dans ce cas précis
    l'utiliateur ne tient pas compte des profils qui lui sont proposés.
end note

user -> app : L'utilisateur peut alors utilisé une barre de recherche pour selectionné des profils en fonctions de divers critères

@enduml