@startuml
autonumber
skinparam sequenceMessageAlign center
skinparam actorStyle hollow

actor "Utilisateur" as user
participant "Application" as app

note over user, app
L’utilisateur inscrit et authentifié
end note

user -> app : L'utilisateur appuie sur un bouton pour voir toutes les notifications qu'il a reçu
app -> user : Affiche les notifications

@enduml