@startuml
autonumber
skinparam sequenceMessageAlign center
skinparam actorStyle hollow

actor "Utilisateur" as user
participant "Application" as app

note over user, app
L’utilisateur inscrit et authentifié et les autres profils aussi.
end note

user -> app : L'utilisateur lance une recherche de profils
app -> app : Recherche de profil en fonction des critères de selection
app -> user : Affichage des profils

@enduml