@startuml
autonumber
skinparam sequenceMessageAlign center
skinparam actorStyle hollow

actor "Utilisateur" as user
participant "Application" as app
participant "AdresseMail" as adresseMail

note over user, adresseMail
L’utilisateur est déjà inscrit
end note

user -> app : l'utilisateur utilise un bouton pour réinitialiser son mot de passe
app -> app : verifie si un utilisateur est associé au login
alt La demande de réinitialiser n'est pas associé à un login valide
    app -> user : Affiche une erreur
end
app -> adresseMail : Envoie sur l'adresse mail de l'utilisateur un lien pour réinitialiser son mot de passe
@enduml
