@startuml
autonumber
skinparam sequenceMessageAlign center
skinparam actorStyle hollow

actor "Utilisateur" as user
participant "Application" as app

note over user, app
L’utilisateur inscrit et authentifié et les autres profils aussi.
end note

alt : L'utilisateur utilise modifie mes critères de recherche
user -> app : appuie sur le boutons "Filtre"
app -> user : ouvre un menu déroulant avec la liste des filtres
user -> app : effectue ou non des modifications
app -> app : enregistre les modifications
end


user -> app : L'utilisateur lance une recherche de profils
app -> user : L'application propose des profils en fonction des critères de recherhce

@enduml