@startuml
autonumber
skinparam sequenceMessageAlign center
skinparam actorStyle hollow

actor "Utilisateur" as user
participant "Application" as app

note over user, app
L’utilisateur inscrit et authentifié
end note

user -> app : Sélectionne interface pour modifier ses préférences
app -> app : Charge préférences
app -> user : Affiche préférences

loop Tant que l'utilisateur ne veut pas terminer de définir ses préférences
alt L'utilisateur utilise modifie ses critères de recherche

alt Changement proximité géographique
user -> app : Change la proximité géographique
app -> app : Enregistre changement
app -> user : Mise à jour de l'interface
else Changement age
user -> app : Change l'âge
app -> app : Enregistre changement
app -> user : Mise à jour de l'interface
else Changement genre
user -> app : Change le genre
app -> app : Enregistre changement
app -> user : Mise à jour de l'interface
end
end
end

note over user, app
L'utilisateur peut changer la proximité géographique,l'age et le genre des profils qui vont lui être recommandés
end note

@enduml
