@startuml
autonumber
skinparam sequenceMessageAlign center
skinparam actorStyle hollow

actor "Utilisateur" as user
participant "Authentification" as auth
participant "Application" as app

note over user, app
L’utilisateur inscrit et authentifié
end note

user -> app : Demande d’accès au profil
app -> app : Charger infos actuelles
app -> user : Affiche les infos actuelles
user -> app : Sélectionne "Modifier texte de présentation"
user -> app : Soumet nouveau texte de présentation
app -> app : Enregistre nouveau texte de présentation utilisateur
app -> user : texte de présentation mis à jour
@enduml
