@startuml
autonumber
skinparam sequenceMessageAlign center
skinparam actorStyle hollow

actor "Utilisateur" as user
participant "Application" as app

note over user, app
L’utilisateur inscrit et authentifié
end note

user -> app : Appuie sur le bouton "Mes Conversations dans l'interface"
app -> user : Affiche la liste des conversations de l'utilisateur
user -> app : Choisit un de ses conversations
app -> user : Affiche la conversation

loop
alt envoie possible
    user -> app : Envoie un message grâce à la zone de texte
    app -> app : procède a l'envoi du message
    app -> user : Met à jour l'affichage
else envoie impossible car l'utilisateur a été bloqué ou a bloqué l'individu
    app -> user : Message d'erreur "Envoie impossible"
end
end


@enduml