@startuml
autonumber
skinparam sequenceMessageAlign center
skinparam actorStyle hollow

actor "Utilisateur" as user
participant "Application" as app

note over user, app
L’utilisateur n'est pas encore inscrit
end note

user -> app : Remplit formulaire d'inscription
app -> app : Vérifie si toutes les informations sont complètes
loop tant que le formulaire n'est pas correct
    alt Formulaire incomplet
        app -> user : Rejette formulaire et affiche message d'erreur
    else Formulaire complet
        app -> app : Enregistrer le formulaire pour être traiter plus tard par un modérateur
    end
end
@enduml
