@startuml
autonumber
skinparam sequenceMessageAlign center
skinparam actorStyle hollow

actor "Utilisateur" as user
participant "Application" as app

note over user, app
L’utilisateur est déjà inscrit
end note

user -> app : l'utilisateur utilise un bouton pour réinitialiser son mot de passe
app -> app : verifie si un utilisateur est associé au login
loop Tant que la l'email n'est pas valide
alt La demande de réinitialiser n'est pas associé à un login valide
    app -> user : Affiche une erreur
else La demade de réinitialiser est valide
    app -> app : Envoie lien de réinitialiser à l'email associé au login
end
end
@enduml
