@startuml
autonumber
skinparam sequenceMessageAlign center
skinparam actorStyle hollow

actor "Utilisateur" as user
participant "Application" as app

note over user, app
L’utilisateur inscrit et authentifié
end note

user -> app : Demande d’accès au profil
app -> app : Charger infos actuelles
app -> user : Affiche les infos actuelles
user -> app : Sélectionne interface pour modifier ses préférences
user -> app : Modifie l'age des utilisateurs pour les profils recommandés

app -> app : Verifie la validité de l'age proposé
alt L'utilisateur choisit un age invalide
    app -> user : notifie que l'age n'est pas valide
end

app -> app : Met à jour ses données
app -> user : Affiche les données mise à jour



@enduml
