@startuml

left to right direction
title Cas d'utilisation - Tinder

actor Utilisateur

package "Authentification" #LightBlue {

    usecase "Authentification" as auth

}

package "Notification" #LightBlue {

    usecase "Consulter ses notifications" as notif_consult

    Utilisateur -- notif_consult

}

"Notification" ..> auth : <<include>>

@enduml
