@startuml

left to right direction
title Cas d'utilisation - Tinder

actor Utilisateur
actor Messagerie

package "Authentification" #LightBlue {

    usecase "Authentification" as auth

}


package "Message" #LightBlue {

    usecase "Envoyer message privé" as mess_envoyer
    usecase "Consulter messages reçus" as mess_consulter
    usecase "Accéder à la liste de conversations" as mess_liste
    usecase "Bloquer une conversation" as mess_bloquer_conv

    Utilisateur -- mess_bloquer_conv
    Utilisateur -- mess_liste
    Utilisateur -- mess_envoyer

    mess_liste --> mess_consulter

    mess_envoyer --> mess_consulter

    mess_consulter -- Messagerie

}

"Message" ..> auth : <<include>>

@enduml
