@startuml

left to right direction
title Cas d'utilisation - Tinder

actor Moderateur

package "Moderation" #LightBlue {

    usecase "Consulter liste de signalement" as mod_liste
    usecase "Vérifier documents utilisateur" as mod_verif_docs
    usecase "Juger profil signalé" as mod_profil_juge

    Moderateur -- mod_liste
    Moderateur -- mod_verif_docs
    Moderateur -- mod_profil_juge

}

package "Authentification" #LightBlue {

    usecase "Authentification" as auth

}

"Moderation" ..> auth : <<include>>

@enduml
