@startuml
left to right direction

'Acteurs'
actor Utilisateur
actor "Authentification"

package "Infos Utilisateur" #LightBlue {

    usecase "Modifier age" as modif_Age
    usecase "Modifier genre" as modif_Genre
    usecase "Modifier ville" as modif_Ville
    usecase "Modifier Quartier" as modif_Quartier
    usecase "Choisir texte de présentation" as modif_Texte_Presentation
    usecase "Choisir centres d'intérêts" as modif_Centre_Interets
    usecase "Consulter ses photos" as modif_Consultation
    usecase "Ajouter des photos" as modif_Ajouter_Photos
    usecase "Supprimer des photos" as modif_Supprimer_Photos

    Utilisateur -- modif_Genre
    Utilisateur -- modif_Age
    Utilisateur -- modif_Ville
    Utilisateur -- modif_Quartier
    Utilisateur -- modif_Texte_Presentation
    Utilisateur -- modif_Centre_Interets
    Utilisateur -- modif_Consultation

    modif_Consultation -- modif_Ajouter_Photos
    modif_Consultation -- modif_Supprimer_Photos

}

    "Infos Utilisateur" ..|> Authentification : <<include>>

@enduml
