@startuml
left to right direction

'Acteurs'
actor Utilisateur
actor "Service de Messagerie" as Messagerie
actor "Service d'Authentification" as Authentification

package "Message" #LightBlue {

    usecase "Envoyer message privé" as mess_envoyer
    usecase "Consulter messages reçus" as mess_consulter
    usecase "Recevoir nouveau message" as mess_recevoir
    usecase "Signaler conversation" as signal_signaler_conv
    usecase "Bloquer conversation" as signal_bloquer_conv

    Utilisateur -- mess_consulter
    Messagerie -- mess_recevoir

    Utilisateur -- mess_envoyer
    Utilisateur -- signal_bloquer_conv
    Utilisateur -- signal_signaler_conv

    Message .left.> Authentification : <<requis>>

}



@enduml