@startuml
left to right direction

enum Genre {
    Homme
    Femme
}

'--- Classes ---'
class Profil {
    id : entier
    nom : chaîne
    prenom : chaîne
    age : entier
    ville : chaîne
    quartier : chaîne
    textePresentation : chaîne
    centresInterets : liste chaîne
    photos : liste images
    profilsInteressant : HashMap Profil,booléen
    estBloque : booléen
    notifMail : booléen
    agePrefere : entier
    genrePrefere : Genre
    ProximiteGeograhpique: chaîne
    bloqueConversation : HashMap Profil,Profil
    Profil(nom : chaîne, prenom : chaîne, age : entier, genre : Genre, ville : chaîne,
    quartier : chaîne, presentation : chaîne, interets : liste chaîne)
    getId() : entier
    getNom() : chaîne
    getPrenom() : chaîne
    getAge() : entier
    getGenre() : Genre
    getVille() : chaîne
    getQuartier() : chaîne
    getPresentation() : chaîne
    getCentresInterets() : liste de chaîne
    getPhotos() : liste images
    getProfilInterets() : HashMap Profil,booléen
    getEstBloque() : booléen
    getNotifMail() : booléen
    getAgePreferer() : entier
    getGenrePreferer() : Genre
    getProximiteGeographique() : chaîne
    getBloqueConversation() : HashMap Profil,Profil
    mettreAJourProfil(nom : chaîne, prenom : chaîne, age : entier, genre : chaîne, ville : chaîne,
    quartier : chaîne, presentation : chaîne, interets : liste chaîne, photos : liste images) : rien
    setProfilInterets(interets : HashMap Profil,booléen) : rien
    setEstBloque(bloque : booléen) : rien
    setNotifMail(notif : booléen) : rien
    mettreAJourPreferences(agePref : entier, genrePref : Genre, lieuProximite : chaîne) : rien
    setBloqueConversation(bloqueConversation : HashMap Profil,Profil) : rien
    signalerProfil(user : Profil) : rien
    signalerMessage(message : Message) : rien
    envoyerMessage(destinataire : Profil, contenu : chaîne) : rien
    modifierMessage(message : Message, contenu : chaîne) : rien
    supprimerMessage(message : Message) : rien
    supprimerNotification(notification : Notification) : rien
    possibleMatch(binome : Profil) : booléen
    peutEnvoyerMessage(destinataire : Profil) : booléen
    ajoutInteresser(user : Profil) : rien
    rechercher(chaîne... profils) : liste Profil
}

class Message {
    contenu : chaîne
    getContenu() : chaîne
    getExpediteur() : Profil
    getDestinataire() : Profil
    setContenu(contenu : chaîne) : rien
}

class Notification {
    contenu : chaîne
    envoi()
    getContenu() : chaîne
    getDestinataire() : Profil
    setContenu(contenu : chaîne) : rien
    setDestinataire(dest : Profil) : rien
}

class Match {
    Match(user1 : Profil, user2 : Profil)
    getUser1() : Profil
    getUser2() : Profil
}

class Signalement {
    id : entier
    raisonSignalement : chaîne
    Signalement(user : Profil)
    Signalement(user : Profil, message : Message)
}

class Moderateur {
    id : entier
    nom : chaîne
    Moderateur(id : entier, nom : chaîne)
    verifierSignalement(signalement : Signalement) : rien
    bloquerProfil(profil : Profil) : rien
    communiquer(profil : Profil) : rien
    verifierInscription(compte : Compte) : booléen
}


class Compte {
    pseudo : chaîne
    email : chaîne
    motDePasse : chaîne
    document : image
    inscrire(email : chaîne, pseudo : chaîne, mdp : chaîne) : rien
    connecter(psuedo : chaîne, email : chaîne, mdp : chaîne) : booléen
    reinitialiserMotDePasse(newMdp : chaîne) : rien
}

class Main{
    main(String args[]) : rien
}

enum TypeNotif{
    Message
    Interet
    Match
    Profil
}


'--- Relations ---'
Profil "1" -- "0..*" Message : expediteur
Profil "1" -- "0..*" Message : destinataire
Profil "2" -- "0..*" Match : intéressé
Profil "1" <-- "0..*" Signalement : victime
Profil "1" <-- "0..*" Signalement : fautif
Moderateur "1" --> "0..*" Signalement : verifieSignalement
Message "0..1" <-- "1" Signalement : messageOffensant
Profil "1" -- "0..*" Notification : reçoit
Profil "0..*" -- "1" Genre : identifieComme
Compte "0..*" <-- "1" Moderateur : verifierDocument
Compte "0..1" -- "1" Profil : connexion
Notification "0..*" -- "1" TypeNotif : type
'(Classe pour une liste de profils recommandés)'
Profil "0..*" -- "0..*" Profil : recommendations
Main "1" ---> "1" Compte : application

@enduml