@startuml

left to right direction
title Cas d'utilisation - Tinder

actor Utilisateur

package "Authentification" #LightBlue {

    usecase "Authentification" as auth

}

package "Signalement" #LightBlue {

    usecase "Signaler un utilisateur" as signal_user
    usecase "Signaler contenu déplacé" as signal_deplace
    usecase "Signaler contenu offensant" as signal_offensant

    Utilisateur -- signal_user
    Utilisateur -- signal_deplace
    Utilisateur -- signal_offensant

}

"Signalement" ..> auth : <<include>>

@enduml
