@startuml

left to right direction
title Cas d'utilisation - Tinder

actor Moderateur


package "Moderation" #LightBlue {

    usecase "Bloquer un profil signalé" as mod_bloquer
    usecase "Vérifier documents utilisateur" as mod_verif_docs
    usecase "Verifier signalement" as mod_verif_signal

    Moderateur -- mod_bloquer
    Moderateur -- mod_verif_docs
    Moderateur -- mod_verif_signal

    mod_bloquer -- mod_verif_signal

}

package "Authentification" #LightBlue {

    usecase "Authentification" as auth

}

"Moderation" ..> auth : <<include>>

@enduml
