@startuml

left to right direction
title Cas d'utilisation - Tinder

actor Utilisateur
actor Messagerie

package "Authentification" #LightBlue {

    usecase "Authentification" as auth

}

package "Message" #LightBlue {

    usecase "Envoyer message privé" as mess_envoyer
    usecase "Consulter ses conversation " as mess_consulter
    usecase "Bloquer une conversation" as mess_bloquer_conv

    Utilisateur -- mess_bloquer_conv
    Utilisateur -- mess_consulter
    Utilisateur -- mess_envoyer

    mess_consulter -- Messagerie

}

"Message" ..> auth : <<include>>

@enduml
