@startuml
left to right direction
"Utilisateur( Acteur principal) " as User
"Moderateur ( Acteur principal ) " as Moderator
"Tinder" as (AppliDeRencontire)

User --> (AppliDeRencontire)
Moderator --> (AppliDeRencontire)
@enduml