@startuml

left to right direction
title Cas d'utilisation - Tinder

actor Utilisateur

package "Authentification" #LightBlue {

    usecase "Authentification" as auth

}

package "Recommandation" #LightBlue {

    usecase "Consulter profil recommandé " as reco_consultation
    usecase "Recherche profil" as reco_recherche
    usecase "swipe droite" as reco_interet
    usecase "envoyer premier message" as reco_message

    Utilisateur -- reco_message
    Utilisateur -- reco_consultation
    Utilisateur -- reco_interet
    Utilisateur -- reco_recherche
    reco_interet -- reco_recherche

}

"Recommandation" ..> auth : <<include>>

@enduml
