@startuml
left to right direction
"Utilisateur" as User
"Messagerie" as Messaging
"BDD" as Database
"Notification" as Notification
"Authentification_peut_etre" as Auth
"Moderateur" as Moderator
"Tinder" as (DatingSystem)

User --> (DatingSystem)
Messaging --> (DatingSystem)
Database --> (DatingSystem)
Notification --> (DatingSystem)
Auth --> (DatingSystem)
Moderator --> (DatingSystem)
@enduml