@startuml

left to right direction
title Cas d'utilisation - Tinder

actor Utilisateur

package "Authentification" #LightBlue {

    usecase "Authentification" as auth

}

package "Signalement" #LightBlue {

    usecase "Signaler un utilisateur" as signal_user

    Utilisateur -- signal_user

}

"Signalement" ..> auth : <<include>>

@enduml
