@startuml

left to right direction

'Acteurs'
actor Utilisateur
actor Moderateur
actor Authentification


package "Moderation" #LightBlue {

    usecase "Vérifier document d'identité" as auth_verif_identite

}

package "Authentifier" #LightBlue {

    usecase "S'inscrire" as auth_inscription
    usecase "Réinitialiser mot de passe" as auth_reset_mdp

    Utilisateur -- auth_inscription
    auth_inscription -- auth_verif_identite : <<requis>>
    auth_verif_identite ..|> Moderateur : <<include>>
    Utilisateur -- auth_reset_mdp

}

Authentifier -- "Authentification"
Moderation -- "Authentification"


@enduml
