@startuml
left to right direction
package "Config Utilisateur" #LightBlue {

    usecase "Modifier ville" as modif_Ville
    usecase "Modifier Quartier" as modif_Quartier
    usecase "Choisir texte de présentation" as modif_Texte_Presentation
    usecase "Choisir centres d'intérêts" as modif_Centre_Interets
    usecase "Consulter ses photos" as modif_Consultation
    usecase "Ajouter des photos" as modif_Ajouter_Photos
    usecase "Supprimer des photos" as modif_Supprimer_Photos
    usecase "Définir ses préferences" as modif_pref
    usecase "Proximite géographique" as modif_proximite
    usecase "Modifier préférence age" as modif_age
    usecase "Modifier préférence genre " as modif_genre
    usecase "Définir sa visiblité" as modif_critere_visibilite_autres
    usecase "Configuration notifications" as modif_notif
    usecase "Configurer envoi par email" as modif_email
    usecase "Choisir son age" as modif_son_age
    usecase "Choisir son genre" as modif_son_genre

    modif_proximite --> modif_pref : <<include>>

    modif_genre --> modif_pref : <<include>>

    modif_age --> modif_pref : <<include>>

    Utilisateur -- modif_email

    modif_email --> modif_notif : <<include>>
    Utilisateur -- modif_Ville
    Utilisateur -- modif_Quartier
    Utilisateur -- modif_Texte_Presentation
    Utilisateur -- modif_Centre_Interets
    Utilisateur -- modif_Supprimer_Photos
    Utilisateur -- modif_Ajouter_Photos
    Utilisateur -- modif_genre
    Utilisateur -- modif_age
    Utilisateur -- modif_proximite
    Utilisateur -- modif_critere_visibilite_autres
    Utilisateur -- modif_notif
    Utilisateur -- modif_son_age
    Utilisateur -- modif_son_genre

    modif_Supprimer_Photos --> modif_Consultation : <<include>>
    modif_Ajouter_Photos --> modif_Consultation : <<include>>

}
@enduml
