@startuml

left to right direction
title Cas d'utilisation - Tinder

actor Utilisateur
actor Messagerie
actor Moderateur

package "Authentification" #LightBlue {

    usecase "Authentification" as auth

}

package "Moderation" #LightBlue {

    usecase "Bloquer un profil signalé" as mod_bloquer
    usecase "Vérifier documents utilisateur" as mod_verif_docs
    usecase "Verifier signalement" as mod_verif_signal

    Moderateur -- mod_bloquer
    Moderateur -- mod_verif_docs
    Moderateur -- mod_verif_signal

    mod_bloquer -- mod_verif_signal

}

package "Signalement" #LightBlue {

    usecase "Signaler un utilisateur" as signal_user
    usecase "Signaler contenu déplacé" as signal_deplace
    usecase "Signaler contenu offensant" as signal_offensant

    Utilisateur -- signal_user
    Utilisateur -- signal_deplace
    Utilisateur -- signal_offensant

}

package "Message" #LightBlue {

    usecase "Envoyer message privé" as mess_envoyer
    usecase "Consulter messages reçus" as mess_consulter
    usecase "Accéder à la liste de conversations" as mess_liste
    usecase "Bloquer une conversation" as mess_bloquer_conv

    Utilisateur -- mess_bloquer_conv
    Utilisateur -- mess_liste
    Utilisateur -- mess_envoyer

    mess_liste --> mess_consulter

    mess_envoyer --> mess_consulter

    mess_consulter -- Messagerie

}

package "Notification" #LightBlue {

    usecase "Consulter ses notifications" as notif_consult
    usecase "Configurer envoi par email" as notif_email

    Utilisateur -- notif_consult
    Utilisateur -- notif_email

}

package "Config Utilisateur" #LightBlue {

    usecase "Modifier age" as modif_Age
    usecase "Modifier genre" as modif_Genre
    usecase "Modifier ville" as modif_Ville
    usecase "Modifier Quartier" as modif_Quartier
    usecase "Choisir texte de présentation" as modif_Texte_Presentation
    usecase "Choisir centres d'intérêts" as modif_Centre_Interets
    usecase "Consulter ses photos" as modif_Consultation
    usecase "Ajouter des photos" as modif_Ajouter_Photos
    usecase "Supprimer des photos" as modif_Supprimer_Photos
    usecase "Définir ses préferences" as modif_pref
    usecase "Proximite géographique" as modif_proximite
    usecase "Choisir age" as modif_age
    usecase "Choisir genre" as modif_genre
    usecase "Rechercher profil" as modif_critere_visibilite_autres
    usecase "Configuration notifications" as modif_notif
    usecase "Se definir" as modif_definir

    modif_proximite --> modif_pref : <<include>>

    modif_genre --> modif_definir : <<include>>
    modif_genre --> modif_pref : <<include>>

    modif_age --> modif_definir : <<include>>
    modif_age --> modif_pref : <<include>>

    Utilisateur -- modif_Age
    Utilisateur -- modif_Genre
    Utilisateur -- modif_Ville
    Utilisateur -- modif_Quartier
    Utilisateur -- modif_Texte_Presentation
    Utilisateur -- modif_Centre_Interets
    Utilisateur -- modif_Supprimer_Photos
    Utilisateur -- modif_Ajouter_Photos
    Utilisateur -- modif_genre
    Utilisateur -- modif_age
    Utilisateur -- modif_proximite
    Utilisateur -- modif_critere_visibilite_autres
    Utilisateur -- modif_notif

    modif_Supprimer_Photos --|> modif_Consultation : <<include>>

    modif_Ajouter_Photos --|> modif_Consultation : <<include>>

}

package "Recommandation" #LightBlue {

    usecase "Consulter profil recommandé " as reco_consultation
    usecase "Recherche profil" as reco_recherche
    usecase "swipe droite" as reco_interet
    usecase "envoyer premier message" as reco_message

    Utilisateur -- reco_message
    Utilisateur -- reco_consultation
    Utilisateur -- reco_interet
    Utilisateur -- reco_recherche
    reco_interet -- reco_recherche

}

package "Authentifier" #LightBlue {

    usecase "S'inscrire" as auth_inscription
    usecase "Réinitialiser mot de passe" as auth_reset_mdp

    Utilisateur -- auth_inscription
    Utilisateur -- auth_reset_mdp

}

"Recommandation" ..> auth : <<include>>
"Config Utilisateur"  ..> auth : <<include>>
"Notification" ..> auth : <<include>>
"Message" ..> auth : <<include>>
"Signalement" ..> auth : <<include>>
"Moderation" ..> auth : <<include>>

@enduml
