@startuml

left to right direction
title Cas d'utilisation - Tinder

actor Utilisateur

package "Authentification" #LightBlue {

    usecase "Authentification" as auth

}

package "Authentifier" #LightBlue {

    usecase "S'inscrire" as auth_inscription
    usecase "Réinitialiser mot de passe" as auth_reset_mdp

    Utilisateur -- auth_inscription
    Utilisateur -- auth_reset_mdp

}
@enduml
